### ISSUE TITLE
withdraw를 제외한 로직 구현

### ISSUE THREAD

**Issue by Seomingyun** [QuinoaDao/protocol-v1#13]
## **Describe the task**

1월 26일 @wakii 와 논의 후 withdraw 로직에 비해 우선적으로 구현해야할 사항들 정리

**Related task**

#6

## **To do**
- [x] withdrawal queue 추가
- [x] active/inactive 모드 추가
- [x] maxDeposit 상한선 100dollar로 설정
- [x] 이 외의 logic들 추가

**Comment by wakii** [comment]
issue close 할게요~
