### ISSUE TITLE
automation setting

### ISSUE THREAD

**Issue by wakii** [QuinoaDao/protocol-v1#21]
## **Describe the task**

rebalance()를 호출할 keeper integration setting
**Related task**

## **To do**
- [ ] keeperCompatible integration
- [ ] CheckUpkeep 구현
- [ ] performUpKeep 구현

## **Additional context**

- Deploy 이후 chainlink 내에서 automation setting 가능

**Comment by Seomingyun** [comment]
반영해서 dev에 merge 됌
