### ISSUE TITLE
Strategy 세부 로직 구현

### ISSUE THREAD

**Issue by Seomingyun** [QuinoaDao/protocol-v1#6]
## **Describe the task**

rebalancing에서 이용될 strategy의 세부적인 로직 구현

**Related task**

- vault 관련 : #1 , #3
- #4 

## **To do**
- [x] withdraw
- [x] deposit
- [x] total asset

## **Additional context**

관련 노션
https://www.notion.so/quinoaprotocol/MVP-1-Smart-contract-3b28624b5e27433ab08796a1d473d658

**Comment by wakii** [comment]
issue close 할게요~
